### ISSUE TITLE
it looks like one of our wp replacement steps is doing the work of two

### ISSUE THREAD

**Issue by arc3x** [Rust-Proof/rustproof#154]
```
---------------------
processing statement	tmp0 = var0
into predicate		((((temp0 : i32) + (5)) == ((x : int) + (5))) && (((temp0 : i32) + (5)) < (2147483647)))
new predicate		((((x : i32) + (5)) == ((x : int) + (5))) && (((x : i32) + (5)) < (2147483647)))
---------------------
processing statement	var0 = arg0
into predicate		((((x : i32) + (5)) == ((x : int) + (5))) && (((x : i32) + (5)) < (2147483647)))
new predicate		((((x : i32) + (5)) == ((x : i32) + (5))) && (((x : i32) + (5)) < (2147483647)))
---------------------
```
The first replacement should only do temp0->var0
The second should to the to argument

This might have been a design choice I missed.

**Comment by salterm** [comment]
I think this is the correct behavior, if var0's and arg0's names are both "x". You may notice that only temp0 is changed in the first step to (x : i32), and in the second step the (x : int) is changed to (x : i32).

Or perhaps you thought that we were treating local variables like temps, and they were just being called "var#" (where # is the index)? It might be better to do that so that we don't have confusion like this over which variable is getting replaced (especially since we don't do type checking at the moment).

**Comment by arc3x** [comment]
fixed
