### ISSUE TITLE
Using a boolean function argument in an if condition causes system failure with terrible error message

### ISSUE THREAD

**Issue by arc3x** [Rust-Proof/rustproof#219]
```
#[condition(pre="true", post="true")]
fn complex_if(x: bool) {
    if  x {
        assert!(1 < 0)
    } else {
        assert!(1 > 0)
    }
}
```
errors with
`thread 'rustc' panicked at 'internal error: entered unreachable code', libsmt.rs/src/logics/qf_abv.rs:19`

I dont see how that code is unreachable. And if it is how can it enter it. lol

**Comment by bajr** [comment]
Please include the error message in this issue.

**Comment by arc3x** [comment]
sorry. Its useless.
`thread 'rustc' panicked at 'internal error: entered unreachable code', libsmt.rs/src/logics/qf_abv.rs:19`

**Comment by salterm** [comment]
This issue seems to happen whenever a boolean variable ends up in the verification condition. The unreachable!() macro is in an expansion of the define_logic!() macro for QF_ABV. The problem seems to be that there is no Boolean type in QF_ABV's "Sorts" enum, but I'm unsure of the best way to deal with this.

**Comment by salterm** [comment]
Fixed with slight change to libsmt.rs, and how we pass boolean variables to it.
