### ISSUE TITLE
Remove overflow/underflow checks from uncheck binary ops

### ISSUE THREAD

**Issue by arc3x** [Rust-Proof/rustproof#221]
Overflow checks are being added to unchecked MIR ops. (eg Add, Sub, ...)

I don't think we want this.

**Comment by bajr** [comment]
Reportedly, the sponsor specifies that this is intentional, since overflow in release rust is undefined.

**Comment by arc3x** [comment]
Wait your saying when we see Add in mir we should still overflow check it like we do when we see CheckedAdd?

**Comment by bajr** [comment]
Yes, because the only difference is in how rust handles the overflow (panics in debug mode, "undefined" in release mode). Both are situations the end user wants to avoid unless they explicitly specify to Rust that they *want* to overflow. I'm not sure if Rustproof handles these explicit overflow statements, but we can worry about that later.

**Comment by arc3x** [comment]
agreed
